"""
MGS2 Animation Import Script for Blender
Generated by MGS2 Animation Capture Tool

To use:
1. Open Blender
2. Go to Scripting tab
3. Open this file and click Run Script
"""

import bpy
import json
from mathutils import Matrix

# HARDCODED PATH - Your capture folder (using fixed file)
JSON_FILE = r"D:\Metal Gear Solid 2\MGS2_Capture\animation_data_fixed.json"

def convert_matrix(dx_matrix):
    """Convert DirectX row-major matrix to Blender column-major matrix"""
    m = Matrix([dx_matrix[0], dx_matrix[1], dx_matrix[2], dx_matrix[3]]).transposed()
    
    # Swap Y and Z axes (Y-up to Z-up)
    conversion = Matrix([
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1]
    ])
    return conversion @ m @ conversion.inverted()

def create_armature(name, bone_count):
    """Create a simple armature with the required number of bones"""
    bpy.ops.object.armature_add(enter_editmode=True)
    armature = bpy.context.object
    armature.name = name
    
    # Clear default bone
    bpy.ops.armature.select_all(action='SELECT')
    bpy.ops.armature.delete()
    
    # Create bones
    amt = armature.data
    for i in range(bone_count):
        bone = amt.edit_bones.new(f"bone_{i:03d}")
        bone.head = (0, 0, i * 0.1)
        bone.tail = (0, 0, i * 0.1 + 0.05)
    
    bpy.ops.object.mode_set(mode='OBJECT')
    return armature

def apply_animation(armature, frames_data, fps=60):
    """Apply animation data to the armature"""
    scene = bpy.context.scene
    scene.render.fps = fps
    scene.frame_start = 0
    scene.frame_end = len(frames_data) - 1
    
    # Create action
    if armature.animation_data is None:
        armature.animation_data_create()
    
    action = bpy.data.actions.new(name="MGS2_Animation")
    armature.animation_data.action = action
    
    # Apply keyframes (every 5th frame to speed up import)
    print("Importing animation... this may take a while for large captures")
    for i, frame_data in enumerate(frames_data):
        if i % 5 != 0:  # Skip frames for speed
            continue
            
        frame_num = frame_data["frame_index"]
        scene.frame_set(frame_num)
        
        for bone_data in frame_data["bone_matrices"]:
            bone_idx = bone_data["bone_index"]
            bone_name = f"bone_{bone_idx:03d}"
            
            if bone_name not in armature.pose.bones:
                continue
            
            pose_bone = armature.pose.bones[bone_name]
            
            # Convert and apply matrix
            dx_matrix = bone_data["matrix"]
            bl_matrix = convert_matrix(dx_matrix)
            pose_bone.matrix = bl_matrix
            
            # Insert keyframes
            pose_bone.keyframe_insert(data_path="location", frame=frame_num)
            pose_bone.keyframe_insert(data_path="rotation_quaternion", frame=frame_num)
        
        if i % 100 == 0:
            print(f"Processed frame {i}...")
    
    print(f"Applied {len(frames_data)} frames to armature")

def main():
    print(f"Loading animation from: {JSON_FILE}")
    
    with open(JSON_FILE, 'r') as f:
        data = json.load(f)
    
    metadata = data["metadata"]
    frames = data["frames"]
    
    print(f"Loaded {metadata['total_frames']} frames with {metadata['bone_count']} bones")
    
    # Determine bone count from actual frame data
    if frames:
        bone_count = len(frames[0]["bone_matrices"])
    else:
        bone_count = metadata["bone_count"]
    
    # Create armature
    armature = create_armature("MGS2_Skeleton", bone_count)
    
    # Apply animation
    apply_animation(armature, frames, fps=int(metadata["frame_rate"]))
    
    print("Animation import complete!")

if __name__ == "__main__":
    main()
